name: CI/CD for matrix.a

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Check code style (Clang-Format)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Clang-Format
        run: sudo apt-get install -y clang-format

      - name: Run Clang-Format check
        run: |
          find . -name "*.c" -o -name "*.h" | xargs clang-format \
          --style=file:materials/linters/.clang-format \
          --dry-run --Werror
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (gcc, check, lcov)
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc check lcov

      - name: Run tests
        working-directory: ./src
        run: |
          make test